#!/usr/bin/env python3
"""
Generate nerdfont_table.hpp from clients/ase-client-web/src/utils/icon-replacer.ts.

The TypeScript file maps every supported ``nf-*`` short name to its real
Unicode glyph (one-character UTF-8 strings). The C++ viewer needs the same
mapping so paragraph rendering can substitute ``(nf-fa-exchange)`` markers
with the actual glyph and a Pango ``<span font_family="Symbols Nerd Font Mono">``
markup wrapper.

Output is a header with a constexpr array of ``{name, utf8}`` entries and a
linear-scan ``lookup_nerdfont`` helper. Linear scan is fine — the table has
under a thousand entries and lookups happen only when paragraph nodes contain
icon markers.

Usage:
    python3 gen_nerdfont_table.py <ts_input> <hpp_output>
"""

import re
import sys
from pathlib import Path


def main() -> int:
    if len(sys.argv) != 3:
        print(
            "usage: gen_nerdfont_table.py <ts_input> <hpp_output>",
            file=sys.stderr,
        )
        return 1

    ts_path = Path(sys.argv[1])
    hpp_path = Path(sys.argv[2])

    if not ts_path.exists():
        print(f"input not found: {ts_path}", file=sys.stderr)
        return 1

    src = ts_path.read_text(encoding="utf-8")
    matches = re.findall(r"'(nf-[^']+)':\s*'([^']+)'", src)
    if not matches:
        print(f"no nf-* entries found in {ts_path}", file=sys.stderr)
        return 1

    lines: list[str] = []
    lines.append("#pragma once")
    lines.append("")
    lines.append("// AUTO-GENERATED by tools/gen_nerdfont_table.py — DO NOT EDIT")
    lines.append(f"// Source: {ts_path.name}")
    lines.append(f"// Entries: {len(matches)}")
    lines.append("")
    lines.append("#include <cstdint>")
    lines.append("")
    lines.append("namespace ase::viewer::render {")
    lines.append("")
    lines.append("struct NerdFontEntry {")
    lines.append("    const char* name;")
    lines.append("    const char* utf8;")
    lines.append("};")
    lines.append("")
    lines.append("inline constexpr NerdFontEntry NERDFONT_TABLE[] = {")
    for name, glyph in matches:
        utf8_bytes = glyph.encode("utf-8")
        hex_escaped = "".join(f"\\x{b:02x}" for b in utf8_bytes)
        lines.append(f'    {{"{name}", "{hex_escaped}"}},')
    lines.append("};")
    lines.append("")
    lines.append(f"inline constexpr uint32_t NERDFONT_COUNT = {len(matches)};")
    lines.append("")
    lines.append("// Linear-scan lookup. Returns the UTF-8 byte sequence for")
    lines.append("// the icon, or nullptr if the name is unknown.")
    lines.append("inline const char* lookup_nerdfont(const char* name, uint32_t name_len) {")
    lines.append("    if (name == nullptr || name_len == 0) return nullptr;")
    lines.append("    for (uint32_t i = 0; i < NERDFONT_COUNT; ++i) {")
    lines.append("        const char* n = NERDFONT_TABLE[i].name;")
    lines.append("        uint32_t j = 0;")
    lines.append("        while (j < name_len && n[j] != '\\0' && n[j] == name[j]) ++j;")
    lines.append("        if (j == name_len && n[j] == '\\0') return NERDFONT_TABLE[i].utf8;")
    lines.append("    }")
    lines.append("    return nullptr;")
    lines.append("}")
    lines.append("")
    lines.append("}  // namespace ase::viewer::render")
    lines.append("")

    hpp_path.parent.mkdir(parents=True, exist_ok=True)
    hpp_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {hpp_path} ({len(matches)} entries)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
